name: "Autoapproval"
description: "Probot application for approving pull requests"
author: "Dmytro Khmelenko"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "arrow-right"
  color: "green"
inputs:
  repository:
    description: "Repository name"
    default: ${{ github.repository }}
  pr_number:
    description: "Pull request number"
